# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
