# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:50
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
