# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170829_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interest',
        ),
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
