# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170901_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='account.UserProfile'),
        ),
    ]
