# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_interest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interest', to='account.Interest'),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interest', to='account.UserProfile'),
        ),
    ]
