# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170901_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_token',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
