# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='device_token',
        ),
    ]
