# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170902_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_token',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
