# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userprofile_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location_lat',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_lon',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
