# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170910_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location_lat',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_lon',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
