# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_userprofile_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_matrix', to='account.Interest')),
                ('interest_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_pair_matrix', to='account.Interest')),
            ],
        ),
    ]
