# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170902_1538'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageRecipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent_message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
            preserve_default=False,
        ),
    ]
